services:
  - type: web
    name: pms-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npx prisma migrate deploy && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: pms-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: http://localhost:5173

databases:
  - name: pms-database
    databaseName: pms_db
    user: pms_user
    plan: free
